# .github/workflows/check.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    permissions:
      checks: write
    uses: robertpsoane/github-workflows/.github/workflows/rust-check.yml@main
    with:
      msrv: 1.82.0
